### ISSUE TITLE
Bot is not responding.

### ISSUE THREAD

**Issue by mr-wh1tehat** [Aleksey-Voko/ChatGPT_Bot#1]
Hey therw, bot is not responding. And it doesn't require any commands?
Btw, can you please show and example of CHAT_ID in config.py file, how it should look like? Maybr this is where I am making mistake. Thanks in advance
Edit: Ok, it was my mistake. I could not set webhook correctly. But now fixed, thanks

**Comment by Aleksey-Voko** [comment]
My version works.
An environment variable must be set in the system.

For example:
`CHAT_ID=123456789`

And it should be added to the `config.py` file to the `WORKS_CHATS` list.

For example:
```
WORKS_CHATS = [
    os.getenv('CHAT_ID'),
]
```
You can add a lot of ID chats to WORKS_CHATS.

For example:
```
WORKS_CHATS = [
    os.getenv('ACHAT_ID'),
    os.getenv('VCHAT_ID'),
    os.getenv('SCHAT_ID'),
    os.getenv('MCHAT_ID'),
]
```
All these ID chats (`ACHAT_ID`, `VCHAT_ID`, `SCHAT_ID`, `MCHAT_ID`) must be set in the OS as environment variables.

This is a list of ID chats in which the bot will work.

In all other chats, he will reply: "Invalid chat ID"
